/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Bird } from './types';

export const birdsList: Bird[] = [
  {
    id: 1,
    name: "臺灣藍鵲",
    scientificName: "Urocissa caerulea",
    englishName: "Taiwan Blue Magpie",
    conservation: "第二級：珍貴稀有",
    elevation: "300m - 1,200m",
    habitat: "中低海拔闊葉林與次生林",
    trivia: "具有強烈的家族合作育雛行為，前幾代孵化的小鳥會留在巢邊幫忙餵奶、照顧下一代弟弟妹妹，被稱為「巢邊幫手」。",
    guide: "成群結隊飛行時，常一隻接一隻劃過樹林間，被賞鳥界雅稱為「長尾陣」或「長尾山娘」。牠們個性強悍，育雛期會主動攻擊走近的人類喔！",
    accentColor: "#2563eb",
    bodyColor: "#1e3a8a",
    chestColor: "#1e40af",
    wingColor: "#3b82f6",
    tailColor: "#f3f4f6", // white/black tipped
    beakColor: "#ef4444", // red beak
    eyeColor: "#fbbf24", // yellow eye
    svgType: "passerine",
    beakType: "pointed",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 2,
    name: "黑長尾雉 (帝雉)",
    scientificName: "Syrmaticus mikado",
    englishName: "Mikado Pheasant",
    conservation: "第二級：珍貴稀有",
    elevation: "1,800m - 3,300m",
    habitat: "高海拔針闊葉混合林與密竹叢",
    trivia: "牠是我們千元新台幣鈔票背面的美麗主角！性情高傲沉穩，在濃霧瀰漫的寒冷高山森林中徐徐漫步，被尊稱為「迷霧中的王者」。",
    guide: "極為羞怯，最容易在大雨過後、晨昏迷霧繚繞的林道邊緣現蹤。公鳥在求偶時會發出輕柔的哨音，並挺胸振翅，羽毛呈高貴的紫藍色金屬光澤。",
    accentColor: "#1e1b4b",
    bodyColor: "#0f172a",
    chestColor: "#1e1b4b",
    wingColor: "#334155",
    tailColor: "#64748b",
    beakColor: "#cbd5e1",
    eyeColor: "#dc2626", // Red bare patch eyes
    svgType: "pheasant",
    beakType: "stout",
    tailType: "spread-pheasant",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ef4444"
  },
  {
    id: 3,
    name: "藍腹鷴",
    scientificName: "Lophura swinhoii",
    englishName: "Swinhoe's Pheasant",
    conservation: "第二級：珍貴稀有",
    elevation: "300m - 2,300m",
    habitat: "中低海拔陰涼茂密的森林底層",
    trivia: "雄鳥身上有非常奪目的金屬藍色，背部有一塊亮眼的雪白羽毛，頭頂也有短白冠。雌鳥則全身斑駁褐色以便在大自然中保護自己。",
    guide: "清晨或黃昏時，牠們常出現在沒有人煙的林道與泥野小徑。走路時步伐輕盈慢條斯理，一旦受驚嚇就會拍打翅膀迅速竄入林間深處。",
    accentColor: "#0369a1",
    bodyColor: "#172554",
    chestColor: "#1e3a8a",
    wingColor: "#1e293b",
    tailColor: "#f8fafc", // white central tail
    beakColor: "#eab308",
    eyeColor: "#b91c1c",
    svgType: "pheasant",
    beakType: "stout",
    tailType: "spread-pheasant",
    hasCrest: true,
    crestColor: "#ffffff",
    hasCheekPatch: true,
    cheekColor: "#ef4444"
  },
  {
    id: 4,
    name: "火冠戴菊",
    scientificName: "Regulus goodfellowi",
    englishName: "Flamecrest",
    conservation: "一般類野生動物",
    elevation: "2,000m - 3,700m",
    habitat: "高海拔針葉林，特別喜愛冷杉與鐵杉",
    trivia: "臺灣體型最小、體重最輕的鳥類之一（約僅 7 克）。當公鳥興奮、求偶或警戒時，頭頂的黃色羽冠會豎起，露出一抹鮮橙紅色的「火焰印記」。",
    guide: "總是像陀螺一樣在冷杉樹枝的頂端不停飛舞、懸停喙食蚜蟲，非常考驗觀察者的專注度。叫聲是極為高頻細碎的「絲、絲」聲。",
    accentColor: "#f97316",
    bodyColor: "#65a30d",
    chestColor: "#facc15",
    wingColor: "#3f6212",
    tailColor: "#4d7c0f",
    beakColor: "#090d16",
    eyeColor: "#ffffff", // white ring list
    svgType: "roundy",
    beakType: "needle",
    tailType: "short-bob",
    hasCrest: true,
    crestColor: "#ea580c",
    hasCheekPatch: true,
    cheekColor: "#111827"
  },
  {
    id: 5,
    name: "栗背林鴝",
    scientificName: "Tarsiger johnstoniae",
    englishName: "Collared Bush Robin",
    conservation: "一般類野生動物",
    elevation: "2,000m - 3,500m",
    habitat: "高山灌葉林、箭竹林與林緣邊坡",
    trivia: "雄鳥有一條優美的白色眉斑，最亮眼的是牠高貴的頸圍，呈鮮豔的橘紅色，像戴著一圈溫暖有質感的亮橘色針織圍巾一樣。",
    guide: "非常大膽好動，常在針葉樹梢或路旁指標上駐足。牠們常一邊歌唱一邊上下快速抖動尾巴，聲音宛如兩顆小石子互敲的「噠、噠」聲。",
    accentColor: "#ea580c",
    bodyColor: "#4b5563",
    chestColor: "#ffedd5",
    wingColor: "#111827",
    tailColor: "#111827",
    beakColor: "#1f2937",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ea580c"
  },
  {
    id: 6,
    name: "臺灣噪眉 (金翼白眉)",
    scientificName: "Trochalopteron morrisonianum",
    englishName: "White-whiskered Laughingthrush",
    conservation: "一般類野生動物",
    elevation: "2,500m - 3,950m",
    habitat: "高山林線周邊、箭竹帶至碎石坡",
    trivia: "臺灣分布海拔最高的特有種鳥類之一。雙眼上下有雪白、粗黑相間的顯眼長眉，嘴角還有兩撇八字白鬍鬚，長相極度有喜感而智慧。",
    guide: "賞鳥人常叫牠「大白眉」或「高山麻雀」。因為超級不怕人，常在合歡山、玉山等風景區的垃圾桶旁或步道上撿拾遊客掉落的碎屑。",
    accentColor: "#b45309",
    bodyColor: "#78350f",
    chestColor: "#d97706",
    wingColor: "#ca8a04",
    tailColor: "#713f12",
    beakColor: "#b45309",
    eyeColor: "#f3f4f6",
    svgType: "passerine",
    beakType: "stout",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ffffff"
  },
  {
    id: 7,
    name: "冠羽畫眉",
    scientificName: "Yuhina brunneiceps",
    englishName: "Taiwan Yuhina",
    conservation: "一般類野生動物",
    elevation: "1,000m - 2,800m",
    habitat: "中海拔常綠闊葉樹林與混生林",
    trivia: "頭頂生長著一頂辨識度超極高的尖聳褐色小蓬冠，遠看像極了頂著前衛帥氣的「龐克頭」。牠們具有「多對夫妻共巢育雛」的社群習性！",
    guide: "牠們的鳴唱聲非常甜美輕快，音似英語口哨「To meet you... (很高興見到你)」，喜歡成群在櫻花樹或山櫻花樹冠層吸食花蜜、嬉鬧。",
    accentColor: "#7c2d12",
    bodyColor: "#854d0e",
    chestColor: "#fef9c3",
    wingColor: "#713f12",
    tailColor: "#a16207",
    beakColor: "#3f1a04",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "short-bob",
    hasCrest: true,
    crestColor: "#7c2d12",
    hasCheekPatch: true,
    cheekColor: "#3f1a04"
  },
  {
    id: 8,
    name: "藪鳥 (黃胸藪眉)",
    scientificName: "Liocichla steerii",
    englishName: "Steere's Liocichla",
    conservation: "一般類野生動物",
    elevation: "1,000m - 2,500m",
    habitat: "中海拔茂密的次生林底層灌木叢",
    trivia: "兩側眼睛前方各有一顆極度耀眼奪目、像貼了亮黃色貼紙一樣的黃橙色「硃砂淚痣」，這也是牠們最迷人的招牌野性防偽標記。",
    guide: "俗稱「溪頭阿嫂」或「黃痣藪眉」，叫聲極為宏亮，高亢悠揚地重複敲擊似「急救、急救」的尖哨。常在森林地表跳躍尋找野莓吃。",
    accentColor: "#ca8a04",
    bodyColor: "#3f6212",
    chestColor: "#facc15",
    wingColor: "#4d7c0f",
    tailColor: "#1e293b",
    beakColor: "#224010",
    eyeColor: "#eab308",
    svgType: "passerine",
    beakType: "stout",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#eab308"
  },
  {
    id: 9,
    name: "白耳畫眉",
    scientificName: "Heterophasia auricularis",
    englishName: "White-eared Sibia",
    conservation: "一般類野生動物",
    elevation: "1,000m - 2,500m",
    habitat: "中高海拔的落葉與長常綠闊葉林 canopy",
    trivia: "從嘴角開端，經過眼部一直延伸到後腦杓，畫著一條飄逸優雅的雪白色纖長細羽，就像兩側耳際掛著閃爍的優雅白鑽耳環、氣質典雅。",
    guide: "鳴聲是高山晨光中最清脆動人的男高音，叫聲多為長距離、迴盪在山谷中的尖銳口哨。熱愛在盛開的櫻花和樟木樹枝端活動。",
    accentColor: "#1e293b",
    bodyColor: "#0f172a",
    chestColor: "#fdba74", // cinnamon color belly
    wingColor: "#1e293b",
    tailColor: "#0f172a",
    beakColor: "#1e293b",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ffffff"
  },
  {
    id: 10,
    name: "臺灣擬啄木 (五色鳥)",
    scientificName: "Psilopogon nuchalis",
    englishName: "Taiwan Barbet",
    conservation: "一般類野生動物",
    elevation: "0m - 1,000m",
    habitat: "低中海拔平地至森林、市區公園樹幹",
    trivia: "全身大部分是鮮綠色，但頭頂和頸部有紅、黃、藍、黑等斑斕彩妝。牠們鳴聲極像敲擊寺廟木魚「郭、郭、郭、郭」，俗稱「花和尚」。",
    guide: "牠們是天生的樹幹木鑿雕刻師，春夏季會選擇枯死的樹幹，用堅硬的黑色大嘴鑿出漂亮的圓形巢洞。在安靜的陽光公園常常能聽到其韻律聲。",
    accentColor: "#22c55e",
    bodyColor: "#16a34a",
    chestColor: "#eab308", // yellow/blue throat
    wingColor: "#2563eb",
    tailColor: "#15803d",
    beakColor: "#0f172a", // heavy bill
    eyeColor: "#ef4444",
    svgType: "kingfisher",
    beakType: "stout",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#06b6d4" // turquoise patch
  },
  {
    id: 11,
    name: "臺灣朱雀",
    scientificName: "Carpodacus formosanus",
    englishName: "Taiwan Rosefinch",
    conservation: "一般類野生動物",
    elevation: "2,200m - 3,500m",
    habitat: "高海拔乾旱灌木林與針葉樹冠層",
    trivia: "雄鳥全身羽色染上了極為奪目的深酒紅至暗玫瑰紅，像極了在大雪或冬霧山野中，一團溫存燃燒跳躍的小煤炭火焰！",
    guide: "雖然羽色搶眼，但在高山碎石或枯葉叢中卻具備驚人的保護保護作用。經常在冷杉毬果或地表啃食嫩芽、草籽，生性十分淡定溫和。",
    accentColor: "#be123c",
    bodyColor: "#9f1239",
    chestColor: "#f43f5e",
    wingColor: "#4c0519",
    tailColor: "#4c0519",
    beakColor: "#78716c",
    eyeColor: "#ffe4e6",
    svgType: "roundy",
    beakType: "stout",
    tailType: "cloven",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 12,
    name: "臺灣噪眉 (臺灣畫眉)",
    scientificName: "Garrulax taewanus",
    englishName: "Taiwan Hwamei",
    conservation: "第二級：珍貴稀有",
    elevation: "0m - 1,000m",
    habitat: "低海拔山區次生林、灌木林和開墾地",
    trivia: "與大陸畫眉最大差異是眼部完全沒有那一圈雪白色羽毛，也就是牠沒有「戴白色眼鏡」。生性機警害羞，叫聲極為婉轉悠揚、百轉千迴。",
    guide: "雖然是臺灣最厲害的野生歌手，但因為面臨雜交威脅和商業捕捉，目前野外數量正大幅在流失。通常在最濃密的草叢下窸窣翻查落葉。",
    accentColor: "#a16207",
    bodyColor: "#854d0e",
    chestColor: "#b45309",
    wingColor: "#a16207",
    tailColor: "#713f12",
    beakColor: "#eab308",
    eyeColor: "#111827",
    svgType: "passerine",
    beakType: "stout",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 13,
    name: "黃山雀",
    scientificName: "Machlolophus holsti",
    englishName: "Yellow Tit",
    conservation: "第二級：珍貴稀有",
    elevation: "1,000m - 2,200m",
    habitat: "中海拔原始闊葉林之大樹樹冠層",
    trivia: "臺灣特有種山雀中唯一有「黑色大羽冠」的貴族。牠的下胸與肚腹呈現極為高飽和的耀眼檸檬黃，尾羽下還有一抹黑藍。在國際極具盛名。",
    guide: "喜歡倒掛在樹梢枝條上細心翻查小蜘蛛與昆蟲。叫聲是一串輕快活潑的「吉、吉、比、吉、吉比」，非常活潑愛動。",
    accentColor: "#facc15",
    bodyColor: "#1e3a8a",
    chestColor: "#fef08a",
    wingColor: "#22d3ee",
    tailColor: "#0f172a",
    beakColor: "#111827",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "cloven",
    hasCrest: true,
    crestColor: "#1e293b",
    hasCheekPatch: true,
    cheekColor: "#ffffff"
  },
  {
    id: 14,
    name: "烏頭翁",
    scientificName: "Pycnonotus taivanus",
    englishName: "Styan's Bulbul",
    conservation: "第二級：珍貴稀有",
    elevation: "0m - 700m",
    habitat: "東部與恆春半島低海拔平原與灌叢",
    trivia: "臺灣本島的特有傳奇。牠與西部常見的白頭翁大小相近，但頭頂前半部覆蓋一頂帥氣「純黑鋼盔帽」，下嘴基還有個可愛的「硃砂紅點」！",
    guide: "只在臺灣的花蓮、台東及恆春半島繁衍。牠們非常外向、不怕人，成大群在桑葚樹和果園上大快朵頤，叫聲像唱歌：「巧克力、巧克力、好巧」。",
    accentColor: "#475569",
    bodyColor: "#64748b",
    chestColor: "#cbd5e1",
    wingColor: "#334155",
    tailColor: "#1e293b",
    beakColor: "#0f172a",
    eyeColor: "#000000",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ef4444" // red dot on chin
  },
  {
    id: 15,
    name: "臺灣小鶯",
    scientificName: "Horornis fortipes robustipes",
    englishName: "Taiwan Bush Warbler",
    conservation: "一般類野生動物",
    elevation: "1,000m - 3,000m",
    habitat: "中高海拔的落葉灌木林與厚實箭竹草原",
    trivia: "身手嬌小且羽色是最樸素的灰橄欖褐色，雖然很難在大地中看出牠，但音量卻堪稱高山喇叭，能唱出非常響亮如拉長音的長哨音！",
    guide: "俗稱「強腳樹鶯」，習慣一邊發出口哨音一邊像小老鼠一樣快速在長滿雜草、竹林地表蛇行滑行，是經典的「只聞其聲難見其人」高手。",
    accentColor: "#a16207",
    bodyColor: "#a16207",
    chestColor: "#eab308",
    wingColor: "#7c2d12",
    tailColor: "#7c2d12",
    beakColor: "#d97706",
    eyeColor: "#000000",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 16,
    name: "赤腹山雀",
    scientificName: "Sittiparus castaneoventris",
    englishName: "Chestnut-bellied Tit",
    conservation: "第二級：珍貴稀有",
    elevation: "300m - 1,800m",
    habitat: "中低海拔成熟溫潤的常綠森林中上層",
    trivia: "頭頂跟胸前被黑、白面部線條點綴，胸前和腹部呈現出極為大膽迷人的「古銅磚紅色」。是山林混群活動中極容易辨識、人氣極高的小精靈。",
    guide: "多以家族為單位，常像馬戲團一樣，倒掛、迴旋、側貼在相思樹或大葉楠枝椏上敲碎昆蟲皮。叫聲是非常神經質悅耳的「滋、滋、滋」細音。",
    accentColor: "#ea580c",
    bodyColor: "#1e293b",
    chestColor: "#c2410c",
    wingColor: "#334155",
    tailColor: "#0f172a",
    beakColor: "#111827",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ffedd5"
  },
  {
    id: 17,
    name: "臺灣竹雞",
    scientificName: "Bambusicola sonorivox",
    englishName: "Taiwan Bamboo Partridge",
    conservation: "一般類野生動物",
    elevation: "0m - 1,200m",
    habitat: "丘陵地、平野茂密竹林與濃密草叢底層",
    trivia: "牠們長得圓滾滾，黑灰的臉旁鑲著紅栗色，喜歡以大群在地表刨土翻葉子找昆蟲與嫩苗。叫聲宏亮無比，常發出經典的「雞狗乖！雞狗乖！」",
    guide: "生性害羞但也相當容易激動。在田埂、竹林深處若聽到「雞狗乖」此起彼落，靜止不動一陣子，牠們可能一整群像小母雞一樣跑出來過馬路哦！",
    accentColor: "#854d0e",
    bodyColor: "#7c2d12",
    chestColor: "#b45309",
    wingColor: "#451a03",
    tailColor: "#451a03",
    beakColor: "#111827",
    eyeColor: "#1e293b",
    svgType: "pheasant",
    beakType: "stout",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#3f1a04"
  },
  {
    id: 18,
    name: "臺灣紫嘯鶇",
    scientificName: "Myophonus insularis",
    englishName: "Taiwan Whistling Thrush",
    conservation: "一般類野生動物",
    elevation: "0m - 2,400m",
    habitat: "陰暗潮濕的林緣溪流、山澗巨石縫或橋墩",
    trivia: "其羽色在普通光線下像純黑色，但只要山谷中的陽光輕柔照亮，全身就會閃現出一層極為高貴神秘、帶有琉璃金屬質感的皇家深紫色。",
    guide: "鳴聲是賞鳥界公認的「老煞車皮聲」，長而尖銳、像沒上油的煞車板在尖叫。平時極愛站在溪流中大石頭上上下抖動尾羽，極具王者架勢。",
    accentColor: "#6366f1",
    bodyColor: "#312e81",
    chestColor: "#1e1b4b",
    wingColor: "#4f46e5",
    tailColor: "#0f172a",
    beakColor: "#0f172a",
    eyeColor: "#d8b4fe",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 19,
    name: "臺灣山鷓鴣 (深山竹雞)",
    scientificName: "Arborophila crudigularis",
    englishName: "Taiwan Partridge",
    conservation: "第三級：其他應予保育",
    elevation: "700m - 2,500m",
    habitat: "中海拔陰暗、富含腐植質的潮濕森林坡地",
    trivia: "牠的眼周外包覆一圈像上了古希臘戲劇妝容的白黑色環帶，喉部有一塊白色大斑。全身長滿細膩神似枯葉與鵝卵石的波浪鱗斑橫斑。",
    guide: "是全臺灣最難親眼見到的陸棲鳥之一！非常害羞且喜愛在森林樹蔭最底部的灌叢緩步遊走，一有動靜就化為無形，鳴聲是沉悶空洞的連續口哨。",
    accentColor: "#1e293b",
    bodyColor: "#475569",
    chestColor: "#94a3b8",
    wingColor: "#1e293b",
    tailColor: "#0f172a",
    beakColor: "#111827",
    eyeColor: "#ffffff",
    svgType: "pheasant",
    beakType: "stout",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ef4444"
  },
  {
    id: 20,
    name: "大冠鷲 (臺灣亞種)",
    scientificName: "Spilornis cheela hoya",
    englishName: "Crested Serpent Eagle",
    conservation: "第二級：珍貴稀有",
    elevation: "0m - 1,500m",
    habitat: "低山丘陵、開墾地至次生林上空常溫熱對流區",
    trivia: "俗稱「蛇鷹」、「吃蛇鳥」。頭頂後方長有黑白相間的羽冠，飛翔時翼下有一條極為顯眼的粗白斑。是臺灣最著名、叫聲最好聽的猛禽。",
    guide: "春夏季炎熱的中午前，常趁氣流在天空中大打空戰，並隨氣流盤旋發出尖銳悠揚如口哨的「忽喲──、忽喲──」悠長叫唱，代表領地主權。",
    accentColor: "#7c2d12",
    bodyColor: "#451a03",
    chestColor: "#7c2d12",
    wingColor: "#1c1917",
    tailColor: "#1c1917",
    beakColor: "#eab308", // Yellow cere
    eyeColor: "#fbbf24", // Yellow eyes
    svgType: "raptor",
    beakType: "hooked",
    tailType: "spread-pheasant",
    hasCrest: true,
    crestColor: "#451a03",
    hasCheekPatch: true,
    cheekColor: "#eab308"
  },
  {
    id: 21,
    name: "鵂鶹 (臺灣最小角鴞)",
    scientificName: "Glaucidium brodiei pardalotum",
    englishName: "Collared Pygmy Owl",
    conservation: "第二級：珍貴稀有",
    elevation: "800m - 2,500m",
    habitat: "中低海拔山林的樹梢、開闊草坡",
    trivia: "大自然中最強、最不可思議的偽裝萌物！體型竟然只有人的拳頭大（約15公分），但後腦杓卻長著一對由黑白羽毛排成的「假眼睛耳羽」！",
    guide: "雖然圓滾滾看起來極為呆萌，但別被騙了：牠是身手敏捷的小型猛禽！會在大白天捕食與牠差不多大的小鳥。鳴音是規律的「吐、吐、吐」聲。",
    accentColor: "#b45309",
    bodyColor: "#78350f",
    chestColor: "#fef3c7",
    wingColor: "#451a03",
    tailColor: "#451a03",
    beakColor: "#fbbf24",
    eyeColor: "#ca8a04",
    svgType: "raptor",
    beakType: "hooked",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#f3f4f6"
  },
  {
    id: 22,
    name: "小剪尾",
    scientificName: "Enicurus scouleri",
    englishName: "Little Forktail",
    conservation: "第三級：其他應予保育",
    elevation: "550m - 2,000m",
    habitat: "清涼乾淨的急流、湧泉、瀑布和多岩石山溪",
    trivia: "全身黑白分明極為雅致，尾羽分叉像一柄秀麗的小黑白剪刀。在充滿水氣的瀑布懸崖巨石上，像一個調皮的白頭小不點一樣在前後點頭擺動。",
    guide: "對水源要求極度嚴苛，只在最零汙染的深山瀑布與湍急小溪活動。在溪流石塊上慢跑，一有動靜就一邊點屁股一邊以極低高度滑過水面。",
    accentColor: "#0f172a",
    bodyColor: "#1e293b",
    chestColor: "#ffffff",
    wingColor: "#0f172a",
    tailColor: "#f8fafc",
    beakColor: "#000000",
    eyeColor: "#ffffff",
    svgType: "kingfisher",
    beakType: "pointed",
    tailType: "cloven",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 23,
    name: "褐鷽",
    scientificName: "Pyrrhula nipalensis uchidai",
    englishName: "Brown Bullfinch",
    conservation: "一般類野生動物",
    elevation: "1,500m - 3,000m",
    habitat: "中高海拔的針樹林或混生灌木層",
    trivia: "牠有一顆像鸚鵡般厚重敦美、呈三角形的灰黑色短嘴。羽毛呈現溫婉迷人的煙灰與泥褐灰，眼睛後有一圈微小的白新月斑，十分文青。",
    guide: "極有教養和安靜。牠們常成對或小群在針葉樹頂啄食毬果、乾果與草籽，鳴聲是非常細微、溫純如悠然哨音的單音「呼… 呼…」。",
    accentColor: "#57534e",
    bodyColor: "#78716c",
    chestColor: "#d6d3d1",
    wingColor: "#292524",
    tailColor: "#1c1917",
    beakColor: "#292524",
    eyeColor: "#ffffff",
    svgType: "roundy",
    beakType: "curved",
    tailType: "cloven",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ffffff"
  },
  {
    id: 24,
    name: "灰喉山椒鳥",
    scientificName: "Pericrocotus solaris",
    englishName: "Gray-chinned Minivet",
    conservation: "第三級：其他應予保育",
    elevation: "1,000m - 2,000m",
    habitat: "中低海拔山地落葉林與闊葉樹林之樹冠層",
    trivia: "兩性外貌反差之最！公鳥身上呈現極艷麗刺眼的硃砂朱紅色配純黑，母鳥則是極亮眼的明黃色配石板灰！成群飛過林梢時，被美譽為「森林紅綠燈」。",
    guide: "非常有家庭秩序，常幾十隻排好隊集體穿越樹冠，像一陣狂風吹拂的彩色楓樹落葉。飛行時會發出極清脆短促的「啾、啾、啾」尖叫。",
    accentColor: "#ea580c",
    bodyColor: "#475569",
    chestColor: "#f97316", // fiery red/yellow depending on male model
    wingColor: "#1e293b",
    tailColor: "#f97316",
    beakColor: "#1e293b",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 25,
    name: "臺灣翠鳥 (魚狗)",
    scientificName: "Alcedo atthis",
    englishName: "Common Kingfisher",
    conservation: "一般類野生動物",
    elevation: "0m - 1,200m",
    habitat: "低海拔乾淨溝渠、魚塘、小溪旁岩石樹枝",
    trivia: "背部覆蓋著宛如神聖藍寶石般的亮金屬鈷藍，腹部為鮮橘色。嘴巴像一把冰冷的黑色大劍，能以破空之速俯衝進水中戳魚，號稱「魚狗」。",
    guide: "常一動不動、像一尊彩色雕像般挺直站在溪畔突出的竹條或枯枝上。一鎖定游魚，即如寶藍色閃電般刺入水面，幾乎百發百中！",
    accentColor: "#059669",
    bodyColor: "#06b6d4",
    chestColor: "#ea580c",
    wingColor: "#0891b2",
    tailColor: "#0e7490",
    beakColor: "#000000", // sword beak
    eyeColor: "#ffffff",
    svgType: "kingfisher",
    beakType: "needle",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ffffff"
  },
  {
    id: 26,
    name: "茶腹鳾",
    scientificName: "Sitta europaea formosana",
    englishName: "Eurasian Nuthatch",
    conservation: "一般類野生動物",
    elevation: "1,000m - 3,000m",
    habitat: "中高海拔成熟健全的大林木樹梢、老樹皮",
    trivia: "臺灣唯一能「頭朝正下方、屁股朝天」倒退、盤旋著沿樹幹往下攀爬的特技鳥類！這都要歸功於牠們極為發達、像鐵鉤一樣的巨大後趾爪。",
    guide: "背部呈現優雅的灰藍色，腹部是淡淡的奶茶淺褐色。牠們速度極快，在厚實的老樟樹皮皺褶中像甲蟲一樣竄爬尋找蟲卵，非常討喜有趣。",
    accentColor: "#38bdf8",
    bodyColor: "#64748b",
    chestColor: "#ffe4e6", // peach-colored underparts
    wingColor: "#475569",
    tailColor: "#334155",
    beakColor: "#1e293b",
    eyeColor: "#ffffff",
    svgType: "kingfisher",
    beakType: "pointed",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#1e293b" // Black eye stripe
  },
  {
    id: 27,
    name: "青背山雀 (特有亞種)",
    scientificName: "Parus monticolus insperatus",
    englishName: "Green-backed Tit",
    conservation: "第二級：珍貴稀有",
    elevation: "1,000m - 2,500m",
    habitat: "中海拔開闊林區、溪谷、步道旁果樹",
    trivia: "背部呈非常飽和的青翠橄欖綠，肚子為黃綠色，最搶眼的是從黑色領喉一路延伸到胯下的黑帶子，簡直像繫著一條優雅帥氣的「黑寬領帶」。",
    guide: "春天是牠們的求偶季，公鳥會飛舞在枝頭發出悅耳甜美的宏亮曲調，常在林木中、巢箱旁好奇探索探頭。",
    accentColor: "#84cc16",
    bodyColor: "#4d7c0f",
    chestColor: "#facc15",
    wingColor: "#1e3a8a",
    tailColor: "#1e293b",
    beakColor: "#111827",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "cloven",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ffffff"
  },
  {
    id: 28,
    name: "黃腹琉璃",
    scientificName: "Niltava vivida",
    englishName: "Vivid Niltava",
    conservation: "一般類野生動物",
    elevation: "1,000m - 2,500m",
    habitat: "中海拔闊葉林頂端枝梢懸崖緣",
    trivia: "公鳥的配色是令人屏息的對比：上半身是如深邃寶石藍夜空般的皇家深藍色，喉腹部則是高飽和、亮晶晶的亮橙黃色，氣宇軒昂。",
    guide: "喜歡站在視野高遠、突出的死樹枝頭上，採取「定點捕捉」方式，看準空中飛蟲，突然像一束霓虹藍光飛出，銜住蟲子再優雅飛回原地啄食。",
    accentColor: "#1d4ed8",
    bodyColor: "#1e3a8a",
    chestColor: "#f97316", // vivid orange
    wingColor: "#3b82f6",
    tailColor: "#172554",
    beakColor: "#0f172a",
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 29,
    name: "白頭鶇 (臺灣特有亞種)",
    scientificName: "Turdus poliocephalus niveiceps",
    englishName: "Island Thrush",
    conservation: "第三級：其他應予保育",
    elevation: "1,800m - 3,000m",
    habitat: "高海拔潮濕茂密的迷霧森林灌木底層",
    trivia: "公鳥的外型對比強烈無比，整顆腦袋像被大雪蓋頂，呈現優雅的純雪白色，但胸口及以下的身體卻是如岩石般的極深古銅焦褐色。",
    guide: "極度害羞且行蹤詭秘。平時都在厚重的林木、蕨類底層地表尋找蚯蚓吃，只有在清晨起霧或夕陽時，才會偶爾跳上柏油路展示驚艷身姿。",
    accentColor: "#78350f",
    bodyColor: "#451a03",
    chestColor: "#3f1a04",
    wingColor: "#1c1917",
    tailColor: "#1c1917",
    beakColor: "#eab308", // Yellow bill
    eyeColor: "#ffffff",
    svgType: "passerine",
    beakType: "pointed",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ffffff" // white whole head
  },
  {
    id: 30,
    name: "綠畫眉",
    scientificName: "Erpornis zantholeuca",
    englishName: "White-bellied Erpornis",
    conservation: "一般類野生動物",
    elevation: "300m - 1,500m",
    habitat: "中低海拔次生林、茂林頂葉中層",
    trivia: "雖叫畫眉，但基因上其實與和攀木鳥、雀類更近。全身呈秀氣、像小抹茶麻薯一樣的淡橄欖綠色，頭頂有秀雅小羽冠，非常斯文。",
    guide: "體型十分嬌小敏捷，常與其他山雀、繡眼混群活動，發出極微弱細緻的「唧、唧、唧」聲。在繁林中極像一片隨風晃動的綠葉。",
    accentColor: "#84cc16",
    bodyColor: "#a3e635",
    chestColor: "#f7fee7",
    wingColor: "#65a30d",
    tailColor: "#4d7c0f",
    beakColor: "#ca8a04",
    eyeColor: "#ffffff",
    svgType: "roundy",
    beakType: "needle",
    tailType: "short-bob",
    hasCrest: true,
    crestColor: "#a3e635",
    hasCheekPatch: false
  },
  {
    id: 31,
    name: "臺灣畫眉 (無印畫眉)",
    scientificName: "Garrulax taewanus",
    englishName: "Taiwan Laughingthrush",
    conservation: "第二級：珍貴稀有",
    elevation: "0m - 1,000m",
    habitat: "平地、丘陵低山林道旁的草生茂密灌叢",
    trivia: "全體呈現樸質無比的沙褐色、棕褐色羽毛，沒有白眼圈和眉線。牠的聲音卻是森林中最悠揚、轉調最複雜的歌手，擅長模仿其他鳥鳴！",
    guide: "因為擅長鳴唱、極度聰明，但也正面臨被大量獵捕出售和野外白頰畫眉基因雜交的生存浩劫，在臺灣低山區非常需要我們的保育呵護。",
    accentColor: "#ca8a04",
    bodyColor: "#b45309",
    chestColor: "#d97706",
    wingColor: "#854d0e",
    tailColor: "#7c2d12",
    beakColor: "#fbbf24",
    eyeColor: "#78350f",
    svgType: "passerine",
    beakType: "stout",
    tailType: "long-taper",
    hasCrest: false,
    hasCheekPatch: false
  },
  {
    id: 32,
    name: "仙八色鶇 (八色鳥)",
    scientificName: "Pitta nympha",
    englishName: "Fairy Pitta",
    conservation: "第二級：珍貴稀有",
    elevation: "0m - 1,000m",
    habitat: "低海拔陰暗多地表腐植、水源乾淨的闊葉林",
    trivia: "鳥中童話精靈！身上有：綠、藍、紅、黃、白、黑、栗、褐等絕美的八種艷麗大自然色彩！尤其是背部的那一抹螢光翡翠綠藍，璀璨無比。",
    guide: "這是一隻非常神秘的名貴夏候鳥，每年春季四、五月自南方遷徙來臺灣育雛，八、九月離去。常在地表濕泥中優雅踱步覓食，叫聲是清幽的兩聲哨音。",
    accentColor: "#0284c7",
    bodyColor: "#0284c7", // Bright cyan strip
    chestColor: "#facc15", // bright yellow
    wingColor: "#15803d", // emerald green
    tailColor: "#dc2626", // red vent strip
    beakColor: "#000000",
    eyeColor: "#ffffff",
    svgType: "kingfisher",
    beakType: "stout",
    tailType: "short-bob",
    hasCrest: false,
    hasCheekPatch: true,
    cheekColor: "#ef4444" // reddish details
  }
];
